#spring:
#  cloud:
#    config:
#      label: develop

server:
  port: 8084
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
jwt:
  secret: 0194cc426c227da58721b57cdde3fc8b6se4cr67et1k56ey9
  token-url: 
    validate: http://customer-service/validate
    
restaurant:
  service:
    search-url:
      restaurant: http://restaurant-service/restaurants/{restaurantId}
    review-url: 
      restaurant: http://restaurant-service/restaurant/{restaurantId}/review
      
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.springframework: ERROR
    com.eatza: DEBUG